export const AUTH_REGISTER_URI = "https://ethertix.co.uk/api/v1/auth/register"
export const AUTH_LOGIN_URI = "https://ethertix.co.uk/api/v1/auth/login"
export const AUTH_VERIFY_EMAIL_URI = "https://ethertix.co.uk/api/v1/auth/verify-email"
export const AUTH_VERIFY_LOGIN_MFA_URI = "https://ethertix.co.uk/api/v1/auth/send-login-mfa"
export const AUTH_RESEND_EMAIL_VERIFICATION_URI = "https://ethertix.co.uk/api/v1/auth/resend-email-verification"