FROM node:alpine AS builder
ARG DEVMODE=dev
WORKDIR '/app'
COPY package.json .
COPY tsconfig.json .
RUN npm install --silent
COPY . .
EXPOSE 3000
RUN npm run build
CMD [ "npm", "run", "start:server" ]

FROM nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]