FROM node:alpine AS builder
ARG DEVMODE=dev
WORKDIR '/app'
COPY package.json .
COPY nodemon.json .
COPY tsconfig.json .
RUN npm install --silent
COPY . .
EXPOSE 3000
RUN npm run build
CMD [ "npm", "run", "start:server" ]

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html