export const FETCH_BOOKINGS_REQUEST = "FETCH_BOOKINGS_REQUEST";
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAIL = "FETCH_BOOKINGS_FAIL";

export const FETCH_SINGLE_BOOKING_REQUEST = "FETCH_SINGLE_BOOKING_REQUEST";