export const FETCH_BOOKINGS_REQUEST = "FETCH_BOOKINGS_REQUEST";
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAIL = "FETCH_BOOKINGS_FAIL";

export const FETCH_SINGLE_BOOKING_REQUEST = "FETCH_SINGLE_BOOKING_REQUEST";
export const FETCH_SINGLE_BOOKING_SUCCESS = "FETCH_SINGLE_BOOKING_SUCCESS";
export const FETCH_SINGLE_BOOKING_FAIL = "FETCH_SINGLE_BOOKING_FAIL";

export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";

export const EDIT_BOOKING_DETAILS_REQUEST = "EDIT_BOOKING_DETAILS_REQUEST";
export const EDIT_BOOKING_DETAILS_SUCCESS = "EDIT_BOOKING_DETAILS_SUCCESS";
export const EDIT_BOOKING_DETAILS_FAIL = "EDIT_BOOKING_DETAILS_FAIL";

export const DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAIL = "DELETE_BOOKING_FAIL";