export const FETCH_ALL_COUPONS_REQUEST = "FETCH_ALL_COUPONS_REQUEST";
export const FETCH_ALL_COUPONS_SUCCESS = "FETCH_ALL_COUPONS_REQUEST";
export const FETCH_ALL_COUPONS_FAIL = "FETCH_ALL_COUPONS_FAIL";