export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const FETCH_EVENTS_REQUEST_SUCCESS = 'FETCH_EVENTS_REQUEST_SUCCESS'
export const FETCH_EVENTS_REQUEST_FAIL = 'FETCH_EVENTS_REQUEST_FAIL';