export const EVENTS_URI = `http://localhost:5301/api/v1/events`

export const FETCH_ALL_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const FETCH_ALL_EVENTS_REQUEST_SUCCESS = 'FETCH_EVENTS_REQUEST_SUCCESS'
export const FETCH_ALL_EVENTS_REQUEST_FAILURE  = 'FETCH_EVENTS_REQUEST_FAIL';

export const FETCH_SINGLE_EVENT_REQUEST = 'FETCH_SINGLE_EVENT_REQUEST';
export const FETCH_SINGLE_EVENT_SUCCESS = 'FETCH_SINGLE_EVENT_REQUEST';
export const FETCH_SINGLE_EVENT_FAILURE = 'FETCH_SINGLE_EVENT_REQUEST';

export const CREATE_NEW_EVENT_REQUEST = "CREATE_NEW_EVENT_REQUEST";
export const CREATE_NEW_EVENT_SUCCESS = "CREATE_NEW_EVENT_SUCCESS";
export const CREATE_NEW_EVENT_FAIL = "CREATE_NEW_EVENT_SUCCESS"