export const FETCH_ALL_EVENTS_REQUEST = 'FETCH_ALL_EVENTS_REQUEST';
export const FETCH_ALL_EVENTS_SUCCESS = 'FETCH_ALL_EVENTS_SUCCESS';
export const FETCH_ALL_EVENTS_FAIL  = 'FETCH_ALL_EVENTS_FAIL';

export const FETCH_SINGLE_EVENT_REQUEST = 'FETCH_SINGLE_EVENT_REQUEST';
export const FETCH_SINGLE_EVENT_SUCCESS = 'FETCH_SINGLE_EVENT_SUCCESS';
export const FETCH_SINGLE_EVENT_FAILURE = 'FETCH_SINGLE_EVENT_FAILURE';

export const FETCH_TRENDING_EVENTS_REQUEST = "FETCH_TRENDING_EVENTS_REQUEST";
export const FETCH_TRENDING_EVENTS_SUCCESS = "FETCH_TRENDING_EVENTS_SUCCESS";
export const FETCH_TRENDING_EVENTS_FAIL = "FETCH_TRENDING_EVENTS_FAIL";

export const FETCH_POPULAR_EVENTS_REQUEST = "FETCH_POPULAR_EVENTS_REQUEST";
export const FETCH_POPULAR_EVENTS_SUCCESS = "FETCH_POPULAR_EVENTS_SUCCESS";
export const FETCH_POPULAR_EVENTS_FAIL = "FETCH_POPULAR_EVENTS_FAIL";

export const CREATE_NEW_EVENT_REQUEST = "CREATE_NEW_EVENT_REQUEST";
export const CREATE_NEW_EVENT_SUCCESS = "CREATE_NEW_EVENT_SUCCESS";
export const CREATE_NEW_EVENT_FAIL = "CREATE_NEW_EVENT_SUCCESS"

export const EDIT_EVENT_REQUEST = "EDIT_EVENT_REQUEST";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAIL = "EDIT_EVENT_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const UPLOAD_EVENT_PHOTO_REQUEST = "UPLOAD_EVENT_PHOTO_REQUEST";
export const UPLOAD_EVENT_PHOTO_SUCCESS = "UPLOAD_EVENT_PHOTO_SUCCESS";
export const UPLOAD_EVENT_PHOTO_FAIL = "UPLOAD_EVENT_PHOTO_FAIL";

export const LIKE_EVENT_REQUEST = "LIKE_EVENT_REQUEST";
export const LIKE_EVENT_SUCCESS = "LIKE_EVENT_SUCCESS";
export const LIKE_EVENT_FAIL = "LIKE_EVENT_FAIL";

export const UNLIKE_EVENT_REQUEST = "UNLIKE_EVENT_REQUEST";
export const UNLIKE_EVENT_SUCCESS = "UNLIKE_EVENT_SUCCESS";
export const UNLIKE_EVENT_FAIL = "UNLIKE_EVENT_FAIL";

export const BOOKMARK_EVENT_REQUEST = "BOOKMARK_EVENT_REQUEST";
export const BOOKMARK_EVENT_SUCCESS = "BOOKMARK_EVENT_SUCCESS";
export const BOOKMARK_EVENT_FAIL = "BOOKMARK_EVENT_FAIL";