export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAIL = "FETCH_REVIEWS_FAIL";

export const FETCH_SINGLE_REVIEW_BY_ID_REQUEST = "FETCH_SINGLE_REVIEW_BY_ID_REQUEST";
export const FETCH_SINGLE_REVIEW_BY_ID_SUCCESS = "FETCH_SINGLE_REVIEW_BY_ID_SUCCESS";
export const FETCH_SINGLE_REVIEW_BY_ID_FAIL = "FETCH_SINGLE_REVIEW_BY_ID_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

export const EDIT_REVIEW_BY_ID_REQUEST = "EDIT_REVIEW_BY_ID_REQEUST";
export const EDIT_REVIEW_BY_ID_SUCCESS = "EDIT_REVIEW_BY_ID_SUCCESS";
export const EDIT_REVIEW_BY_ID_FAIL = "EDIT_REVIEW_BY_ID_FAIL";

export const DELETE_REVIEW_BY_ID_REQUEST = "DELETE_REVIEW_BY_ID_REQUEST";
export const DELETE_REVIEW_BY_ID_SUCCESS = "DELETE_REVIEW_BY_ID_SUCCESS";