export const FETCH_ALL_TICKETS_REQUEST = "FETCH_ALL_TICKETS_REQUEST";
export const FETCH_ALL_TICKETS_SUCCESS = "FETCH_ALL_TICKETS_SUCCESS";
export const FETCH_ALL_TICKETS_FAIL = "FETCH_ALL_TICKETS_FAIL";

export const FETCH_SINGLE_TICKET_REQUEST = "FETCH_SINGLE_TICKET_REQUEST";
export const FETCH_SINGLE_TICKET_SUCESS = "FETCH_SINGLE_TICKET_REQUEST"
export const FETCH_SINGLE_TICKET_FAIL = "FETCH_SINGLE_TICKET_FAIL"

export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";

export const EDIT_TICKET_REQUEST = "EDIT_TICKET_REQUEST";
export const EDIT_TICKET_SUCCESS = "EDIT_TICKET_SUCCESS";
export const EDIT_TICKET_FAIL = "EDIT_TICKET_FAIL";