export const FETCH_ALL_TICKETS_REQUEST = "FETCH_ALL_TICKETS_REQUEST";
export const FETCH_ALL_TICKETS_SUCCESS = "FETCH_ALL_TICKETS_SUCCESS";
export const FETCH_ALL_TICKETS_FAIL = "FETCH_ALL_TICKETS_FAIL";

export const FETCH_SINGLE_TICKET_REQUEST = "FETCH_SINGLE_TICKET_REQUEST";