export const FETCH_VENUES_REQUEST = "FETCH_VENUES_REQUEST";
export const FETCH_VENUES_SUCCESS = "FETCH_VENUES_REQUEST";
export const FETCH_VENUES_FAIL = "FETCH_VENUES_REQUEST";

export const FETCH_SINGLE_VENUE_REQUEST = "FETCH_SINGLE_VENUE_REQUEST";
export const FETCH_SINGLE_VENUE_SUCCESS = "FETCH_SINGLE_VENUE_SUCCESS";
export const FETCH_SINGLE_VENUE_FAIL = "FETCH_SINGLE_VENUE_FAIL";

export const CREATE_NEW_VENUE_REQUEST = "CREATE_NEW_VENUE_REQUEST";
export const CREATE_NEW_VENUE_SUCCESS = "CREATE_NEW_VENUE_SUCCESS";
export const CREATE_NEW_VENUE_FAIL = "CREATE_NEW_VENUE_FAIL";