export const FETCH_VENUES_REQUEST = "FETCH_VENUES_REQUEST";
export const FETCH_VENUES_SUCCESS = "FETCH_VENUES_REQUEST";
export const FETCH_VENUES_FAIL = "FETCH_VENUES_FAIL";

export const FETCH_SINGLE_VENUE_REQUEST = "FETCH_SINGLE_VENUE_REQUEST";
export const FETCH_SINGLE_VENUE_SUCCESS = "FETCH_SINGLE_VENUE_SUCCESS";
export const FETCH_SINGLE_VENUE_FAIL = "FETCH_SINGLE_VENUE_FAIL";

export const CREATE_NEW_VENUE_REQUEST = "CREATE_NEW_VENUE_REQUEST";
export const CREATE_NEW_VENUE_SUCCESS = "CREATE_NEW_VENUE_SUCCESS";
export const CREATE_NEW_VENUE_FAIL = "CREATE_NEW_VENUE_FAIL";

export const EDIT_VENUE_DETAILS_REQUEST = "EDIT_VENUE_DETAILS_REQUEST";
export const EDIT_VENUE_DETAILS_SUCCESS = "EDIT_VENUE_DETAILS_SUCCESS";
export const EDIT_VENUE_DETAILS_FAIL = "EDIT_VENUE_DETAILS_FAIL";

export const DELETE_VENUE_DETAILS_REQUEST = "DELETE_VENUE_DETAILS_REQUEST";
export const DELETE_VENUE_DETAILS_SUCCESS = "DELETE_VENUE_DETAILS_SUCCESS";
export const DELETE_VENUE_DETAILS_FAIL = "DELETE_VENUE_DETAILS_FAIL";